# -*- coding: ascii -*-
# SNIPERFC-AGENT-V5-OK
"""
SNIPER FC V5 - local Selenium agent.

This file is generated by the web console. Do not edit it.
The launcher injects BASE_URL and AGENT_KEY automatically.
"""

import os
import platform
import random
import threading
import time

import requests
from selenium import webdriver
from selenium.common.exceptions import TimeoutException, WebDriverException
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait


BASE_URL = "http://localhost:3000"
AGENT_KEY = "dev-agent-key"
CHROME_PROFILE = ""

AGENT_VERSION = "5.0"
WEB_APP_URL = "https://www.ea.com/fr-fr/ea-sports-fc/ultimate-team/web-app/"
POLL_SECONDS = 1.0
HEARTBEAT_SECONDS = 5.0

DEFAULT_ENGINE = {
    "maxIncrement": 16,
    "refreshMinLoops": 400,
    "refreshMaxLoops": 500,
    "loopDelayMs": 400,
    "buyLimit": 0,
    "floodThreshold": 6,
    "autoRefreshMin": 15,
    "minCreditsFloor": 0,
    "status": "running",
}

DEFAULT_STRATEGY = {
    "id": None,
    "name": "Default",
    "playerName": "",
    "playerEnabled": False,
    "buyPrice": 1000,
    "sellMin": 1100,
    "sellMax": 1200,
    "rarity": "",
    "rarityEnabled": False,
    "quality": "Gold",
    "qualityEnabled": False,
    "position": "",
    "positionEnabled": False,
}

FILTER_KEYS = (
    "id",
    "playerName",
    "playerEnabled",
    "buyPrice",
    "rarity",
    "rarityEnabled",
    "quality",
    "qualityEnabled",
    "position",
    "positionEnabled",
)


class SniperFCV5:
    def __init__(self):
        self.engine = dict(DEFAULT_ENGINE)
        self.strategy = dict(DEFAULT_STRATEGY)
        self.driver = None

        self.paused = False
        self.stopped = False
        self.must_refresh = False
        self.must_restart = False
        self.market_ready = False

        self.loops = 0
        self.refresh_count = 0
        self.increment_value = 0
        self.buys = 0
        self.credits = None
        self.next_refresh = 450
        self.last_refresh_at = time.time()
        self.last_heartbeat_at = 0.0
        self.last_quiet_log_at = 0.0
        self.api_online = False
        self._unauth_count = 0
        self.lock = threading.Lock()
        self.http = self.build_session()
        # Anti zombie-stop : un ancien ordre d'arret (status=stopped
        # persistant ou commande stop non consommee) ne doit pas tuer un
        # agent qui vient de demarrer. Grace les STOP_IGNORE_SECONDS
        # premieres secondes, le serveur a le temps de se rearmer.
        self.started_at = time.time()
        self.grace_seconds = 20.0

    def stop_allowed(self):
        return (time.time() - self.started_at) > self.grace_seconds

    # ------------------------------------------------------------------
    # Values and timing
    # ------------------------------------------------------------------
    def engine_int(self, key):
        try:
            return int(self.engine.get(key, DEFAULT_ENGINE.get(key, 0)) or 0)
        except (TypeError, ValueError):
            return int(DEFAULT_ENGINE.get(key, 0) or 0)

    def strategy_int(self, key):
        try:
            return int(self.strategy.get(key, DEFAULT_STRATEGY.get(key, 0)) or 0)
        except (TypeError, ValueError):
            return 0

    def strategy_str(self, key):
        value = self.strategy.get(key, DEFAULT_STRATEGY.get(key, ""))
        return "" if value is None else str(value)

    def strategy_bool(self, key):
        return bool(self.strategy.get(key, DEFAULT_STRATEGY.get(key, False)))

    @staticmethod
    def sleep_between(low, high=None):
        time.sleep(low if high is None else random.uniform(low, high))

    def schedule_refresh(self):
        low = max(10, self.engine_int("refreshMinLoops"))
        high = max(10, self.engine_int("refreshMaxLoops"))
        if low > high:
            low, high = high, low
        self.next_refresh = random.randint(low, high)

    # ------------------------------------------------------------------
    # Web console API
    # ------------------------------------------------------------------
    def build_session(self):
        """HTTP session with browser-like headers so hosting firewalls
        (Vercel bot protection, Cloudflare, proxies) do not block the agent."""
        session = requests.Session()
        session.headers.update({
            "x-agent-key": AGENT_KEY,
            "Content-Type": "application/json",
            "Accept": "application/json, text/plain, */*",
            "Accept-Language": "fr-FR,fr;q=0.9,en;q=0.8",
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/122.0.0.0 Safari/537.36 SNIPERFC/5.0"
            ),
        })
        return session

    def check_console(self):
        """Startup connectivity probe with explicit, readable output."""
        print("Connexion a la console : %s" % BASE_URL, flush=True)
        try:
            response = self.http.get(BASE_URL + "/api/agent/poll", timeout=10)
        except Exception as error:
            print("  [ECHEC] Console injoignable : %s" % error, flush=True)
            print("  Verifie ton acces internet ou l'URL du site.", flush=True)
            return False

        body = response.text[:400].strip()
        vercel_gate = (
            "authentication required" in body.lower()
            or "vercel" in body.lower() and "<" in body
        )

        if response.status_code == 401 and vercel_gate:
            print("  [ECHEC] Ton URL Vercel est un deploiement PREVIEW protege.", flush=True)
            print("  Ses API exigent une connexion au compte Vercel : l'agent ne", flush=True)
            print("  peut jamais y acceder, quelle que soit la cle.", flush=True)
            print("", flush=True)
            print("  SOLUTION (au choix) :", flush=True)
            print("    a) Utilise le domaine PRODUCTION du site (sans le hash", flush=True)
            print("       aleatoire, ex : ton-projet.vercel.app), ou", flush=True)
            print("    b) Vercel > Settings > Deployment Protection > desactive-le,", flush=True)
            print("       puis regenere le launcher.", flush=True)
            print("", flush=True)
            print("  L'agent reste actif et reessaiera en boucle.", flush=True)
            return False

        if response.status_code == 401:
            print("  [ECHEC] Cle refusee (401). Detail serveur :", flush=True)
            print("  " + (body[:200] or "(reponse vide)"), flush=True)
            print("  Regenere le launcher depuis l'onglet Connexion.", flush=True)
            return False

        content_type = response.headers.get("content-type", "")
        if response.status_code != 200 or "application/json" not in content_type:
            print(
                "  [ECHEC] Reponse inattendue : HTTP %s (%s)"
                % (response.status_code, content_type or "type inconnu"),
                flush=True,
            )
            print("  Debut de la reponse :", flush=True)
            print("  " + (body[:200] or "(reponse vide)"), flush=True)
            return False

        print("  [OK] Console joignable. Agent reconnu.", flush=True)
        return True

    def report(self, *events):
        try:
            self.http.post(
                BASE_URL + "/api/agent/report",
                json={"events": list(events)},
                timeout=8,
            )
        except Exception:
            pass

    def log(self, message, level="info"):
        now = time.strftime("%H:%M:%S")
        print("[%s] [%-5s] %s" % (now, level.upper(), message), flush=True)
        self.report({"type": "log", "level": level, "message": message})

    def quiet_log(self, message):
        if time.time() - self.last_quiet_log_at >= 12:
            self.last_quiet_log_at = time.time()
            self.log(message)

    def heartbeat(self, force=False, status=None):
        now = time.time()
        if not force and now - self.last_heartbeat_at < HEARTBEAT_SECONDS:
            return
        self.last_heartbeat_at = now
        self.report({
            "type": "heartbeat",
            "status": status or ("paused" if self.paused else "running"),
            "credits": self.credits,
            "loops": self.loops,
            "refreshCount": self.refresh_count,
            "incrementValue": self.increment_value,
            "nextRefreshIn": max(0, self.next_refresh - self.refresh_count),
            "platform": "%s %s" % (platform.system(), platform.release()),
            "version": AGENT_VERSION,
            "name": platform.node() or "Mon PC",
        })

    def apply_command(self, command):
        kind = (command or {}).get("type")
        if kind == "pause":
            self.paused = True
            self.log("Pause received from console", "warn")
        elif kind == "resume":
            self.paused = False
            self.log("Resume received from console", "ok")
        elif kind == "stop":
            if self.stop_allowed():
                self.stopped = True
            else:
                print("Ordre STOP ignore : agent en cours de demarrage.", flush=True)
        elif kind in ("refresh_now", "reload_strategy"):
            self.must_refresh = True
        elif kind == "restart_driver":
            self.must_restart = True
        elif kind == "reset_stats":
            self.loops = 0
            self.refresh_count = 0
            self.increment_value = 0
            self.buys = 0

    def poll_loop(self):
        while not self.stopped:
            try:
                response = self.http.get(
                    BASE_URL + "/api/agent/poll",
                    timeout=8,
                )
                if response.status_code == 401:
                    self._unauth_count += 1
                    if self._unauth_count == 1 or self._unauth_count % 12 == 0:
                        print(
                            "Cle refusee (%d) - l'agent retente toutes les 30 s."
                            % self._unauth_count,
                            flush=True,
                        )
                    self.api_online = False
                    self.sleep_between(30)
                    continue
                self._unauth_count = 0

                response.raise_for_status()
                payload = response.json()
                new_engine = payload.get("engine") or {}
                new_strategy = payload.get("strategy") or {}

                with self.lock:
                    old_filters = tuple(self.strategy.get(k) for k in FILTER_KEYS)
                    self.engine.update(new_engine)
                    if new_strategy:
                        self.strategy = dict(DEFAULT_STRATEGY)
                        self.strategy.update(new_strategy)
                    new_filters = tuple(self.strategy.get(k) for k in FILTER_KEYS)

                    status = str(self.engine.get("status", "running"))
                    self.paused = status == "paused"
                    if status == "stopped" and self.stop_allowed():
                        self.stopped = True

                    if self.api_online and old_filters != new_filters:
                        self.must_refresh = True

                if not self.api_online:
                    self.api_online = True
                    self.log("Console connectee. Configuration chargee.", "ok")
                    self.heartbeat(force=True)

                for command in payload.get("commands") or []:
                    self.apply_command(command)
            except Exception as error:
                if self.api_online:
                    self.api_online = False
                    print("Console injoignable (%s). Nouvel essai..." % error, flush=True)

            self.sleep_between(POLL_SECONDS)

    # ------------------------------------------------------------------
    # Chrome lifecycle
    # ------------------------------------------------------------------
    def open_browser(self):
        if self.driver is not None:
            return

        profile = CHROME_PROFILE.strip()
        if not profile:
            profile = os.path.join(os.getcwd(), "chrome_profile_v5")

        options = webdriver.ChromeOptions()
        options.add_argument("--user-data-dir=" + profile)
        options.add_argument("--no-sandbox")
        options.add_argument("--disable-dev-shm-usage")
        options.add_argument("--disable-blink-features=AutomationControlled")
        options.add_argument("--window-size=1440,1000")
        options.add_experimental_option("excludeSwitches", ["enable-automation"])

        self.driver = webdriver.Chrome(options=options)
        self.driver.get(WEB_APP_URL)
        self.log("Chrome opened. Log in to EA if requested.")
        self.sleep_between(2.0, 3.0)
        self.try_login_button()

    def close_browser(self):
        try:
            if self.driver is not None:
                self.driver.quit()
        except Exception:
            pass
        self.driver = None
        self.market_ready = False

    def restart_browser(self):
        self.log("Restarting Chrome", "warn")
        self.close_browser()
        self.sleep_between(2.0, 3.0)
        self.open_browser()
        self.prepare_market()

    def try_login_button(self):
        try:
            button = WebDriverWait(self.driver, 4).until(
                EC.element_to_be_clickable(
                    (By.XPATH, "//button[contains(normalize-space(.), 'Login')]")
                )
            )
            button.click()
        except Exception:
            pass

    # ------------------------------------------------------------------
    # Market navigation and filters
    # ------------------------------------------------------------------
    def prepare_market(self):
        transfer_button = WebDriverWait(self.driver, 20).until(
            EC.element_to_be_clickable(
                (By.XPATH, "//button[span[normalize-space(text())='Transfers']]")
            )
        )
        transfer_button.click()
        self.sleep_between(0.7, 1.0)

        search_entry = WebDriverWait(self.driver, 15).until(
            EC.element_to_be_clickable(
                (By.XPATH, "//h1[normalize-space(text())='Search the Transfer Market']")
            )
        )
        search_entry.click()
        self.sleep_between(0.8, 1.2)

        self.fill_filters()
        self.refresh_count = 0
        self.increment_value = 0
        self.last_refresh_at = time.time()
        self.schedule_refresh()
        self.market_ready = True

    def select_dropdown(self, label, value):
        if not value:
            return
        try:
            field = WebDriverWait(self.driver, 6).until(
                EC.element_to_be_clickable(
                    (By.XPATH, "//span[@class='label' and normalize-space(text())='%s']" % label)
                )
            )
            field.click()
            option = WebDriverWait(self.driver, 6).until(
                EC.element_to_be_clickable(
                    (By.XPATH, "//li[normalize-space(text())=%s]" % self.xpath_literal(value))
                )
            )
            option.click()
            self.sleep_between(0.2, 0.4)
        except Exception as error:
            self.log("Filter not found: %s = %s (%s)" % (label, value, error), "warn")

    @staticmethod
    def xpath_literal(value):
        if "'" not in value:
            return "'%s'" % value
        if '"' not in value:
            return '"%s"' % value
        parts = value.split("'")
        return "concat(%s)" % ", \"'\", ".join("'%s'" % p for p in parts)

    def fill_filters(self):
        if self.strategy_bool("playerEnabled") and self.strategy_str("playerName"):
            player_input = WebDriverWait(self.driver, 10).until(
                EC.presence_of_element_located((By.CLASS_NAME, "ut-text-input-control"))
            )
            player_input.clear()
            player_input.send_keys(self.strategy_str("playerName"))
            self.sleep_between(0.8, 1.1)
            first_result = WebDriverWait(self.driver, 10).until(
                EC.element_to_be_clickable(
                    (By.XPATH, "(//ul[contains(@class,'playerResultsList')]//button)[1]")
                )
            )
            first_result.click()

        if self.strategy_bool("qualityEnabled"):
            self.select_dropdown("Quality", self.strategy_str("quality"))
        if self.strategy_bool("rarityEnabled"):
            self.select_dropdown("Rarity", self.strategy_str("rarity"))
        if self.strategy_bool("positionEnabled"):
            self.select_dropdown("Position", self.strategy_str("position"))

        max_buy = WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((
                By.XPATH,
                "(//div[contains(@class,'ut-numeric-input-spinner-control')]"
                "/input[contains(@class,'ut-number-input-control')])[4]",
            ))
        )
        max_buy.clear()
        max_buy.send_keys(str(self.strategy_int("buyPrice")))
        self.sleep_between(0.3, 0.5)

        target = self.strategy_str("playerName")
        if not self.strategy_bool("playerEnabled"):
            target = "global market"
        self.log(
            "Strategy loaded: %s / %s / max %s credits"
            % (self.strategy_str("name"), target, self.strategy_int("buyPrice"))
        )

    def refresh_market(self):
        self.log("Refreshing market page")
        self.driver.refresh()
        self.sleep_between(2.0, 3.0)
        self.try_login_button()
        self.prepare_market()

    def increment_search_price(self):
        try:
            if self.increment_value < self.engine_int("maxIncrement"):
                button = WebDriverWait(self.driver, 4).until(
                    EC.element_to_be_clickable((By.CLASS_NAME, "increment-value"))
                )
                button.click()
                self.increment_value += 1
            else:
                field = WebDriverWait(self.driver, 4).until(
                    EC.presence_of_element_located((
                        By.XPATH,
                        "(//div[contains(@class,'ut-numeric-input-spinner-control')]"
                        "/input[contains(@class,'ut-number-input-control')])[1]",
                    ))
                )
                field.clear()
                self.increment_value = 0
        except Exception:
            pass

    def click_search(self):
        button = WebDriverWait(self.driver, 8).until(
            EC.element_to_be_clickable(
                (By.XPATH, "//button[normalize-space(text())='Search']")
            )
        )
        button.click()

    def go_back(self):
        try:
            button = WebDriverWait(self.driver, 6).until(
                EC.element_to_be_clickable(
                    (By.CSS_SELECTOR, "button.ut-navigation-button-control")
                )
            )
            button.click()
            self.sleep_between(0.05, 0.12)
        except Exception:
            self.must_refresh = True

    def read_credits(self):
        try:
            element = WebDriverWait(self.driver, 2).until(
                EC.presence_of_element_located(
                    (By.CLASS_NAME, "view-navbar-currency-coins")
                )
            )
            raw = element.text.replace(" ", "").replace(",", "").replace(".", "")
            self.credits = int(raw)
        except Exception:
            pass
        return self.credits

    # ------------------------------------------------------------------
    # Search result, purchase and relist
    # ------------------------------------------------------------------
    @staticmethod
    def parse_price(text):
        clean = text.replace(" ", "").replace(",", "").replace(".", "")
        return int(clean)

    def collect_results(self):
        try:
            items = WebDriverWait(self.driver, 0.9).until(
                EC.presence_of_all_elements_located(
                    (By.CSS_SELECTOR, "li.listFUTItem")
                )
            )
        except TimeoutException:
            return []

        results = []
        for item in items:
            try:
                values = item.find_elements(
                    By.XPATH, ".//span[@class='currency-coins value']"
                )
                if len(values) >= 3:
                    results.append((self.parse_price(values[2].text), item))
            except Exception:
                continue
        return results

    def report_snapshot(self, count, lowest=None):
        self.report({
            "type": "snapshot",
            "strategyId": self.strategy.get("id"),
            "listingCount": count,
            "lowestPrice": lowest,
        })

    @staticmethod
    def replace_input(element, value):
        element.send_keys(Keys.CONTROL, "a")
        element.send_keys(Keys.DELETE)
        element.send_keys(str(value))

    def purchase_and_relist(self, item, price, market_depth):
        item.click()

        buy_button = WebDriverWait(self.driver, 4).until(
            EC.element_to_be_clickable(
                (By.CSS_SELECTOR, "button.btn-standard.buyButton.currency-coins")
            )
        )
        buy_button.click()

        try:
            WebDriverWait(self.driver, 2).until(
                EC.element_to_be_clickable(
                    (By.XPATH, "//button[span[normalize-space(text())='Ok']]")
                )
            ).click()
        except TimeoutException:
            pass

        list_button = WebDriverWait(self.driver, 4).until(
            EC.element_to_be_clickable(
                (By.XPATH, "//button[span[normalize-space(text())='List on Transfer Market']]")
            )
        )
        list_button.click()
        self.sleep_between(0.2, 0.4)

        min_input = WebDriverWait(self.driver, 8).until(
            EC.presence_of_element_located(
                (By.XPATH, "(//input[contains(@class,'ut-number-input-control')])[1]")
            )
        )
        max_input = WebDriverWait(self.driver, 8).until(
            EC.presence_of_element_located(
                (By.XPATH, "(//input[contains(@class,'ut-number-input-control')])[2]")
            )
        )
        self.replace_input(min_input, self.strategy_int("sellMin"))
        self.sleep_between(0.15, 0.25)
        self.replace_input(max_input, self.strategy_int("sellMax"))
        self.sleep_between(0.15, 0.25)

        WebDriverWait(self.driver, 8).until(
            EC.element_to_be_clickable(
                (By.XPATH, "//button[normalize-space(text())='List for Transfer']")
            )
        ).click()

        player = self.strategy_str("playerName")
        if not player or not self.strategy_bool("playerEnabled"):
            player = "Market card"

        self.buys += 1
        self.report({
            "type": "purchase",
            "strategyId": self.strategy.get("id"),
            "player": player,
            "buyPrice": price,
            "sellMin": self.strategy_int("sellMin"),
            "sellMax": self.strategy_int("sellMax"),
            "marketDepth": market_depth,
        })
        self.log(
            "BOUGHT %s for %s, relisted for %s"
            % (player, price, self.strategy_int("sellMax")),
            "buy",
        )

    def scan_and_buy(self):
        results = self.collect_results()
        if not results:
            self.report_snapshot(0, None)
            return False

        results.sort(key=lambda pair: pair[0])
        lowest_price, lowest_item = results[0]
        market_depth = len(results)
        self.report_snapshot(market_depth, lowest_price)

        flood_limit = max(2, self.engine_int("floodThreshold"))
        if market_depth >= flood_limit:
            self.paused = True
            self.report({
                "type": "market_flood",
                "message": "Auto pause: %s cards at %s credits (possible market dump)"
                % (market_depth, lowest_price),
            })
            return False

        if lowest_price > self.strategy_int("buyPrice"):
            self.quiet_log(
                "Lowest price %s is above configured maximum" % lowest_price
            )
            return False

        credits = self.read_credits()
        if credits is not None:
            if credits < lowest_price:
                self.quiet_log("Not enough credits")
                return False
            floor = self.engine_int("minCreditsFloor")
            if floor > 0 and credits - lowest_price < floor:
                self.paused = True
                self.report({
                    "type": "low_credits",
                    "message": "Auto pause: credit floor reached (%s)" % floor,
                })
                return False

        self.purchase_and_relist(lowest_item, lowest_price, market_depth)

        buy_limit = self.engine_int("buyLimit")
        if buy_limit > 0 and self.buys >= buy_limit:
            self.paused = True
            self.report({
                "type": "buy_limit",
                "message": "Auto pause: buy limit reached (%s)" % buy_limit,
            })

        self.heartbeat(force=True)
        return True

    # ------------------------------------------------------------------
    # Main loop
    # ------------------------------------------------------------------
    def ensure_market_ready(self):
        announced = False
        while not self.stopped and not self.market_ready:
            # On continue de signaler notre presence a la console pendant
            # l'attente : le badge reste vert et pause/stop restent utilisables.
            self.heartbeat(force=True, status="waiting_login")
            if self.paused:
                self.sleep_between(2.0)
                continue
            try:
                self.prepare_market()
            except Exception:
                if not announced:
                    announced = True
                    self.log(
                        "En attente : connecte-toi a ton compte EA dans Chrome, "
                        "puis laisse la fenetre ouverte.",
                        "warn",
                    )
                self.sleep_between(5)
        if self.market_ready:
            self.log("Marche des transferts pret. Chasse en cours.", "ok")

    def run(self):
        print("SNIPER FC Agent V5 demarre...", flush=True)
        self.check_console()

        # Signale la presence AVANT le thread de poll : le serveur rearme
        # un eventuel status=stopped restant d'une session precedente.
        self.heartbeat(force=True, status="starting")
        self.log("Agent V5 connecte a la console.", "ok")

        threading.Thread(target=self.poll_loop, daemon=True).start()
        self.sleep_between(0.8)

        self.open_browser()
        self.heartbeat(force=True, status="browser_ready")
        self.ensure_market_ready()

        while not self.stopped:
            if self.paused:
                self.heartbeat()
                self.sleep_between(1.5, 2.2)
                continue

            try:
                if self.must_restart:
                    self.must_restart = False
                    self.restart_browser()

                minutes_since_refresh = (time.time() - self.last_refresh_at) / 60.0
                refresh_due = (
                    self.must_refresh
                    or self.refresh_count >= self.next_refresh
                    or minutes_since_refresh >= self.engine_int("autoRefreshMin")
                )
                if refresh_due:
                    self.must_refresh = False
                    self.refresh_market()

                self.increment_search_price()
                self.click_search()
                self.scan_and_buy()
                self.go_back()
                self.read_credits()

                self.loops += 1
                self.refresh_count += 1
                self.heartbeat()

                delay = max(0.1, self.engine_int("loopDelayMs") / 1000.0)
                self.sleep_between(delay * 0.8, delay * 1.3)

            except WebDriverException as error:
                self.log("Chrome error: %s" % str(error)[:120], "error")
                try:
                    self.restart_browser()
                except Exception:
                    self.close_browser()
                    self.sleep_between(6)
                    self.open_browser()
                    self.ensure_market_ready()
            except Exception as error:
                self.log("Loop error: %s" % error, "warn")
                self.must_refresh = True
                self.sleep_between(1.0, 1.5)

        self.heartbeat(force=True, status="stopped")
        self.close_browser()
        print("SNIPER FC Agent V5 arrete.", flush=True)


def main():
    agent = SniperFCV5()
    try:
        agent.run()
    except KeyboardInterrupt:
        print("Arret de l'agent V5...", flush=True)
        agent.stopped = True
        agent.close_browser()
    except Exception as error:
        print("Erreur fatale agent V5 : %s" % error, flush=True)
        agent.close_browser()
        raise


if __name__ == "__main__":
    main()
